# Numpy - Numeriacl Python


## 1. Numpy Array


### List와 넘파이 어레이 속도 비교

In [9]:
import numpy as np 
np_arr = np.arange(100000)

In [10]:
nu_list = []
for i in range(100000):
    nu_list.append(i)

In [11]:
nu_list =[i for i in range(100000)]


In [12]:
%%time
for i in range(100):
    sum(nu_list)

Wall time: 102 ms


In [13]:
%%time
for i in range(200):
    np.sum(np_arr)

Wall time: 7.48 ms


### 1차원 배열 (array) 만들기

In [15]:
vector = np.array([1,4,7,10], float)
vector

array([ 1.,  4.,  7., 10.])

In [17]:
type(vector)

numpy.ndarray

In [18]:
vector.shape

(4,)

### 2창원 배열 만들기

In [21]:
matrix = np.array([[1,2,3,5], [2,3,4,9],[4,5,6,7]])
matrix

array([[1, 2, 3, 5],
       [2, 3, 4, 9],
       [4, 5, 6, 7]])

In [22]:
matrix.shape

(3, 4)

### 3차원 배열 만들기

In [27]:
t_list = [[[1,2,5,8], [2,3,4,9], [4,5,6,7]], [[1,2,5,8], [2,3,4,9], [4,5,6,7]], [[1,2,5,8], [2,3,4,9], [4,5,6,7]], [[1,2,5,8], [2,3,4,9], [4,5,6,7]]]
tensor = np.array(t_list)
tensor

array([[[1, 2, 5, 8],
        [2, 3, 4, 9],
        [4, 5, 6, 7]],

       [[1, 2, 5, 8],
        [2, 3, 4, 9],
        [4, 5, 6, 7]],

       [[1, 2, 5, 8],
        [2, 3, 4, 9],
        [4, 5, 6, 7]],

       [[1, 2, 5, 8],
        [2, 3, 4, 9],
        [4, 5, 6, 7]]])

In [30]:
tensor.shape

(4, 3, 4)

### Array Shape


## ndim & size

In [32]:
vector.ndim, matrix.ndim, tensor.ndim

(1, 2, 3)