Numpy Indexing & Slicing

In [2]:
a_list = [[1,2,3], ['a', 'b', 'c']]
a_list[1][1]

'b'

In [5]:
import numpy as np 
a_arr = np.array([[1,2,3],[4,5,6]])
a_arr[1][1]

5

In [7]:
a_arr[1,1]


5

In [9]:
# 리스트는 안됨 에러남
a_list[1,1]

TypeError: list indices must be integers or slices, not tuple

In [24]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]], int)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
a[:2, :2]


array([[1, 2],
       [5, 6]])

In [26]:
a[1:, 1:3]

array([[ 6,  7],
       [10, 11]])

In [27]:
a[:, 2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [29]:
a[1:, ::2]

array([[ 5,  7],
       [ 9, 11]])