# Numpy Creation
### arange

In [2]:
import numpy as np 
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [7]:
list(range(0,5, 0.5))

TypeError: 'float' object cannot be interpreted as an integer

In [9]:
np.arange(0, 5, 0.5).tolist()

[0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5]

In [12]:
np.arange(12).reshape(3,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 그래프를 그릴때 사용

x = np.arange(-1,1,100)
y = np.sin(x)


### ones, zeros and empty

In [17]:
np.zeros(shape=(10,), dtype=np.int8) # 원소가 10개인 벡터생성

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [19]:
np.ones((2, 5))   # 2 x 5 –    값이 1인 matrix 생성

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.empty((3, 5))  # 메모리가 초기화되어 있지 않음

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Somethig like

In [23]:
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [24]:
test_matrix = np.arange(30).reshape(5,6)
np.zeros_like(test_matrix)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

### identity (단위 행렬)

In [26]:
np.identity(n=3, dtype=np.int32)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [28]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

###   eye (대각선이 1인 행렬)

In [31]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [33]:
np.eye(3, 5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
np.eye(3, 5, k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

### diag (대각 행렬의 값을 추출)

In [39]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
np.diag(matrix)

array([0, 4, 8])

In [42]:
np.diag(matrix, k=1)

array([1, 5])

### Random sampling(데이터 분포에 따른 sampling으로 array를 생성)

In [43]:
np.random.seed(2021)

In [45]:
np.random.uniform(0, 1, 10).reshape(2,5)

array([[0.0968944 , 0.05857129, 0.96239599, 0.61655744, 0.08662996],
       [0.56127236, 0.61652471, 0.96384302, 0.57430429, 0.37116085]])

In [47]:
np.random.normal(0, 1, 10).reshape(2,5)

array([[ 1.14723599,  1.37626076, -0.47218397,  0.5240849 ,  1.48510793],
       [ 1.48243225,  0.72813051, -0.38964808,  0.27889376,  0.0519002 ]])

In [49]:
np.random.binomial(n, p, size)

NameError: name 'n' is not defined

In [55]:
import matplotlib.pyplot as plt 
rand_norm = np.random.normal(0., 3., size=1000)
count, bins, ignored = plt.hist(rand_norm, normed=False)
unique, counts = np.unique(rand_pois, return_counts=True)
np.asarray((unique, counts)).T
plt.bar(unique, counts, width=0.5, color='red', align='center')

AttributeError: 'Rectangle' object has no property 'normed'

AttributeError: 'Rectangle' object has no property 'normed'